---
abstract: 'Sort lists natural with Sort::Naturally'
author:
  - 'Alexander Wirt <formorer@formorer.de>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Template-Plugin-SortNatural
no_index:
  directory:
    - t
    - inc
requires:
  Template::Plugin::VMethods: '0'
  Test::More: '0'
version: '0.001'
